'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowLeft, Bell, CheckCircle2, Clock3, ExternalLink, Filter, RefreshCw, Search, Send, ShieldAlert, XCircle } from 'lucide-react';
import { adminFetch } from '@/lib/admin-client-auth';

type IncidentStatus = 'open' | 'acknowledged' | 'investigating' | 'resolved';
type Incident = { id:number; fingerprint:string; severity:string; status:IncidentStatus; title:string; message:string; service:string|null; symbol:string|null; model_id:string|null; source_event_id:number|null; first_seen_at:string; last_seen_at:string; acknowledged_at:string|null; investigating_at:string|null; resolved_at:string|null; updated_at:string };
type Summary = Record<IncidentStatus, number>;
type Health = { status?:string; timestamp?:string; services?:{database?:string;dbLatencyMs?:number|null;pythonDaemon?:string;pythonRuntime?:string;daemonLatencyMs?:number|null;runtimeLatencyMs?:number|null} };
const emptySummary: Summary = {open:0,acknowledged:0,investigating:0,resolved:0};

function formatTime(value?:string|null){if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString();}
function severityClass(value:string){return value==='critical'?'border-red-400/20 bg-red-400/10 text-red-200':value==='error'?'border-rose-400/20 bg-rose-400/10 text-rose-200':'border-amber-400/20 bg-amber-400/10 text-amber-200';}
function statusClass(value:IncidentStatus){return value==='resolved'?'text-emerald-300':value==='investigating'?'text-cyan-300':value==='acknowledged'?'text-violet-300':'text-amber-300';}

export default function IncidentCenterPage(){
 const [incidents,setIncidents]=useState<Incident[]>([]),[summary,setSummary]=useState<Summary>(emptySummary),[health,setHealth]=useState<Health|null>(null),[filter,setFilter]=useState<'active'|IncidentStatus>('active'),[severity,setSeverity]=useState<'all'|'critical'|'error'|'warning'>('all'),[service,setService]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<Incident|null>(null),[loading,setLoading]=useState(true),[updating,setUpdating]=useState<number|null>(null),[error,setError]=useState<string|null>(null),[autoRefresh,setAutoRefresh]=useState(true),[lastRefresh,setLastRefresh]=useState<string|null>(null),[testAlertLoading,setTestAlertLoading]=useState(false),[testAlertMsg,setTestAlertMsg]=useState<string|null>(null);

 const load=useCallback(async()=>{setLoading(true);setError(null);try{const [ir,hr]=await Promise.all([adminFetch(`/api/admin/incidents?status=${filter}&limit=100`,{cache:'no-store'}),fetch('/api/health',{cache:'no-store'})]);if(ir.status===401){window.location.replace('/admin');return;}const body=await ir.json().catch(()=>({}));const hb=await hr.json().catch(()=>null);if(!ir.ok)throw new Error(body?.error||`Incident API returned HTTP ${ir.status}.`);setIncidents(Array.isArray(body.incidents)?body.incidents:[]);setSummary({...emptySummary,...(body.summary||{})});setHealth(hb);setLastRefresh(new Date().toISOString());}catch(err){setError(err instanceof Error?err.message:'Unable to load incident state.');}finally{setLoading(false);}},[filter]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!autoRefresh)return;const timer=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(timer);},[autoRefresh,load]);

 async function handleSendTestAlert() {
   setTestAlertLoading(true);
   setTestAlertMsg(null);
   try {
     const res = await adminFetch('/api/admin/test-alert', {
       method: 'POST',
       headers: { 'Content-Type': 'application/json' },
       body: JSON.stringify({ channel: 'all' }),
     });
     const data = await res.json().catch(() => ({}));
     if (!res.ok) throw new Error(data?.error || `Failed to dispatch (HTTP ${res.status})`);
     setTestAlertMsg('✅ Test alert dispatched to Telegram & Email successfully!');
     setTimeout(() => setTestAlertMsg(null), 6000);
   } catch (err: any) {
     setTestAlertMsg(`❌ ${err.message || 'Failed to dispatch alert'}`);
   } finally {
     setTestAlertLoading(false);
   }
 }

 async function transition(id:number,status:IncidentStatus){setUpdating(id);setError(null);try{const r=await adminFetch('/api/admin/incidents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b?.error||`Unable to transition incident (HTTP ${r.status}).`);await load();}catch(err){setError(err instanceof Error?err.message:'Unable to update incident.');}finally{setUpdating(null);}}
 const activeCount=summary.open+summary.acknowledged+summary.investigating;
 const services=useMemo(()=>['all',...Array.from(new Set(incidents.map(i=>i.service||'system'))).sort()],[incidents]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return incidents.filter(i=>severity==='all'||(severity==='warning'?i.severity==='warn':i.severity===i.severity&&i.severity===severity)).filter(i=>service==='all'||(i.service||'system')===service).filter(i=>!q||[i.title,i.message,i.service,i.symbol,i.model_id,String(i.id),i.fingerprint].filter(Boolean).join(' ').toLowerCase().includes(q));},[incidents,severity,service,query]);
 const criticalCount=incidents.filter(i=>i.severity==='critical').length,errorCount=incidents.filter(i=>i.severity==='error').length,warningCount=incidents.filter(i=>i.severity==='warn').length,systemHealthy=health?.status==='healthy';
 const dbStatus = health?.services?.database || 'unknown';
 const mlStatus = health?.services?.pythonRuntime || health?.services?.pythonDaemon || 'unknown';
 const dbLatency = health?.services?.dbLatencyMs != null ? `${health.services.dbLatencyMs} ms` : 'Latency unavailable';
 const mlLatency = (health?.services?.runtimeLatencyMs ?? health?.services?.daemonLatencyMs) != null ? `${health?.services?.runtimeLatencyMs ?? health?.services?.daemonLatencyMs} ms` : 'Latency unavailable';

 return <main className="min-h-screen bg-[#05070b] text-slate-100"><div className="mx-auto max-w-[1600px] px-4 py-5 sm:px-6 lg:px-8">
  <header className="mb-6 rounded-3xl border border-white/10 bg-white/[0.03] p-5 backdrop-blur-xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl border border-red-400/20 bg-red-400/10 p-3"><ShieldAlert className="h-6 w-6 text-red-300"/></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-red-300">Operations · Incident Response</p><h1 className="text-2xl font-black tracking-tight sm:text-3xl">Incident & Alert Center</h1><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-500">Persistent incident lifecycle with source-backed evidence, safe triage filters, and explicit runtime health.</p></div></div><div className="flex flex-wrap items-center gap-2"><button onClick={handleSendTestAlert} disabled={testAlertLoading} className="inline-flex items-center gap-2 rounded-xl border border-amber-400/30 bg-amber-400/10 px-3.5 py-2 text-xs font-semibold text-amber-200 hover:bg-amber-400/20 disabled:opacity-50 transition"><Bell className={`h-4 w-4 ${testAlertLoading ? 'animate-bounce' : ''}`}/>{testAlertLoading ? 'Sending Alert…' : '🔔 Send Test Alert'}</button><Link href="/admin/operational-intelligence" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-slate-300"><ArrowLeft className="h-4 w-4"/>Operational Intelligence</Link><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-cyan-400/20 bg-cyan-400/5 px-3 py-2 text-xs font-semibold text-cyan-200"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button><button onClick={()=>setAutoRefresh(v=>!v)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-slate-300"><Activity className="h-4 w-4"/>Auto {autoRefresh?'ON':'OFF'}</button></div></div>
  {testAlertMsg && <div className={`mt-3 rounded-xl border p-3 text-xs font-medium ${testAlertMsg.startsWith('✅') ? 'border-emerald-400/30 bg-emerald-400/10 text-emerald-200' : 'border-rose-400/30 bg-rose-400/10 text-rose-200'}`}>{testAlertMsg}</div>}
  <div className="mt-4 flex flex-wrap items-center gap-3 text-[10px] text-slate-600"><span>Last refresh: {formatTime(lastRefresh)}</span><span>•</span><span>Polling: {autoRefresh?'15s':'paused'}</span><span>•</span><span>Source: persisted incident state + production health</span></div></header>
  {error&&<div className="mb-5 rounded-2xl border border-red-400/20 bg-red-400/[0.06] p-4 text-sm text-red-200">{error}</div>}
  <section className="mb-5 grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric icon={ShieldAlert} label="Active" value={activeCount} tone="amber"/><Metric icon={XCircle} label="Critical" value={criticalCount} tone="red"/><Metric icon={AlertTriangle} label="Errors" value={errorCount} tone="rose"/><Metric icon={Activity} label="Warnings" value={warningCount} tone="amber"/><Metric icon={systemHealthy?CheckCircle2:XCircle} label="System" value={systemHealthy?1:0} tone={systemHealthy?'emerald':'red'} suffix={systemHealthy?'healthy':'attention'}/></section>
  <section className="mb-5 grid gap-4 lg:grid-cols-3"><StatusCard title="System" value={health?.status||'unknown'} ok={systemHealthy} detail={formatTime(health?.timestamp)}/><StatusCard title="Database" value={dbStatus} ok={dbStatus==='connected'} detail={dbLatency}/><StatusCard title="ML Runtime" value={mlStatus} ok={mlStatus==='connected'} detail={mlLatency}/></section>
  <section className="mb-5 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400"><Filter className="h-4 w-4"/>Triage filters</div><div className="grid gap-3 lg:grid-cols-[1fr_180px_200px]"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search title, message, symbol, model or incident ID" className="w-full rounded-xl border border-white/10 bg-black/20 py-2.5 pl-9 pr-3 text-xs text-slate-200 outline-none focus:border-cyan-400/40"/></label><select value={severity} onChange={e=>setSeverity(e.target.value as typeof severity)} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-xs text-slate-300"><option value="all">All severities</option><option value="critical">Critical</option><option value="error">Errors</option><option value="warning">Warnings</option></select><select value={service} onChange={e=>setService(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-xs text-slate-300">{services.map(s=><option key={s} value={s}>{s==='all'?'All services':s}</option>)}</select></div><div className="mt-4 flex flex-wrap gap-2">{(['active','open','acknowledged','investigating','resolved'] as const).map(v=><button key={v} onClick={()=>setFilter(v)} className={`rounded-xl px-3 py-2 text-xs font-semibold ${filter===v?'bg-cyan-400/10 text-cyan-200 ring-1 ring-cyan-400/20':'bg-white/5 text-slate-500 hover:bg-white/10'}`}>{v==='active'?`Active (${activeCount})`:`${v} (${summary[v]})`}</button>)}</div></section>
  <section className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"><div className="flex items-center justify-between border-b border-white/10 p-4"><div><h2 className="text-sm font-bold">Incident Evidence Queue</h2><p className="mt-1 text-xs text-slate-600">Showing {filtered.length} of {incidents.length} incidents returned by the authoritative incident API.</p></div><Clock3 className="h-4 w-4 text-slate-600"/></div>{loading&&!incidents.length?<div className="p-12 text-center text-sm text-slate-500">Loading incident state…</div>:!filtered.length?<div className="p-12 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-300"/><p className="mt-3 text-sm font-semibold text-slate-300">No incidents match the current view.</p></div>:<div className="divide-y divide-white/5">{filtered.map(i=><div key={i.id} className="p-4"><div className="flex flex-col gap-3 xl:flex-row xl:items-start xl:justify-between"><button type="button" onClick={()=>setSelected(i)} className="min-w-0 flex-1 text-left"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${severityClass(i.severity)}`}>{i.severity==='warn'?'warning':i.severity}</span><span className={`text-[10px] font-bold uppercase tracking-wider ${statusClass(i.status)}`}>{i.status}</span>{i.service&&<span className="text-[10px] uppercase tracking-wider text-slate-600">{i.service}</span>}{i.symbol&&<span className="font-mono text-[10px] text-slate-600">{i.symbol}</span>}</div><h3 className="mt-2 text-sm font-semibold text-slate-200">{i.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{i.message}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 font-mono text-[10px] text-slate-600"><span>#{i.id}</span><span>First: {formatTime(i.first_seen_at)}</span><span>Last: {formatTime(i.last_seen_at)}</span></div></button><div className="flex shrink-0 flex-wrap gap-2 xl:max-w-[360px] xl:justify-end">{i.status==='open'&&<><ActionButton label="Acknowledge" onClick={()=>void transition(i.id,'acknowledged')} disabled={updating===i.id}/><ActionButton label="Investigate" onClick={()=>void transition(i.id,'investigating')} disabled={updating===i.id}/></>}{i.status==='acknowledged'&&<><ActionButton label="Investigate" onClick={()=>void transition(i.id,'investigating')} disabled={updating===i.id}/><ActionButton label="Resolve" onClick={()=>void transition(i.id,'resolved')} disabled={updating===i.id}/></>}{i.status==='investigating'&&<ActionButton label="Resolve" onClick={()=>void transition(i.id,'resolved')} disabled={updating===i.id}/>} {i.status==='resolved'&&<ActionButton label="Reopen" onClick={()=>void transition(i.id,'open')} disabled={updating===i.id}/>}</div></div></div>)}</div>}</section>
  {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-3 backdrop-blur-sm sm:items-center" onClick={()=>setSelected(null)}><article className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl border border-white/10 bg-[#0a0d13] p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-wider ${severityClass(selected.severity)}`}>{selected.severity==='warn'?'warning':selected.severity}</span><span className={`text-[10px] font-bold uppercase tracking-wider ${statusClass(selected.status)}`}>{selected.status}</span></div><h2 className="mt-3 text-lg font-bold">{selected.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{selected.message}</p></div><button type="button" onClick={()=>setSelected(null)} className="rounded-xl border border-white/10 px-3 py-2 text-xs text-slate-400">Close</button></div><dl className="mt-6 grid gap-3 sm:grid-cols-2">{[['Incident ID',String(selected.id)],['Fingerprint',selected.fingerprint],['Service',selected.service||'—'],['Symbol',selected.symbol||'—'],['Model',selected.model_id||'—'],['Source event',selected.source_event_id!=null?String(selected.source_event_id):'—'],['First seen',formatTime(selected.first_seen_at)],['Last seen',formatTime(selected.last_seen_at)],['Acknowledged',formatTime(selected.acknowledged_at)],['Investigating',formatTime(selected.investigating_at)],['Resolved',formatTime(selected.resolved_at)],['Updated',formatTime(selected.updated_at)]].map(([label,value])=><div key={label} className="rounded-xl border border-white/5 bg-white/[0.025] p-3"><dt className="text-[10px] uppercase tracking-wider text-slate-600">{label}</dt><dd className="mt-1 break-all font-mono text-xs text-slate-300">{value}</dd></div>)}</dl><div className="mt-5 flex flex-wrap gap-2"><Link href="/admin/observability" className="inline-flex items-center gap-2 rounded-xl border border-cyan-400/20 bg-cyan-400/5 px-3 py-2 text-xs font-semibold text-cyan-200">Open telemetry <ExternalLink className="h-3.5 w-3.5"/></Link><Link href="/admin/signal-forensics" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-slate-300">Signal forensics <ExternalLink className="h-3.5 w-3.5"/></Link></div></article></div>}
 </div></main>;
}

function Metric({icon:Icon,label,value,tone,suffix}:{icon:typeof Activity;label:string;value:number;tone:string;suffix?:string}){const cls:Record<string,string>={red:'text-red-300',amber:'text-amber-300',rose:'text-rose-300',cyan:'text-cyan-300',emerald:'text-emerald-300'};return <div className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><Icon className={`h-4 w-4 ${cls[tone]||'text-slate-300'}`}/><p className="mt-2 text-[10px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-black">{value}</p>{suffix&&<p className="mt-1 text-[10px] uppercase tracking-wider text-slate-600">{suffix}</p>}</div>;}
function ActionButton({label,onClick,disabled}:{label:string;onClick:()=>void;disabled:boolean}){return <button type="button" onClick={onClick} disabled={disabled} className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-slate-300 transition hover:bg-white/10 disabled:cursor-wait disabled:opacity-50">{disabled?'Updating…':label}</button>;}
function StatusCard({title,value,ok,detail}:{title:string;value:string;ok:boolean;detail:string}){return <div className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{title}</p>{ok?<CheckCircle2 className="h-4 w-4 text-emerald-300"/>:<XCircle className="h-4 w-4 text-red-300"/>}</div><p className="mt-2 text-lg font-bold">{value}</p><p className="mt-1 text-xs text-slate-600">{detail}</p></div>;}
